"""Initial migration

Revision ID: acdd9d1542b0
Revises:
Create Date: 2026-01-26 21:19:52.058112

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "acdd9d1542b0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
