"""add_users_table_and_songs_fk

Revision ID: d1e8089d8f36
Revises: acdd9d1542b0
Create Date: 2026-01-29 11:09:56.273761

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1e8089d8f36"
down_revision: str | Sequence[str] | None = "acdd9d1542b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "midi_songs", "users", ["user_id"], ["id"], ondelete="CASCADE")
    op.add_column("users", sa.Column("anthropic_api_key_sha256", sa.String(length=64), nullable=False))
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_anthropic_api_key_sha256"), "users", ["anthropic_api_key_sha256"], unique=True)
    op.drop_column("users", "email")
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column("users", sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_users_anthropic_api_key_sha256"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_column("users", "anthropic_api_key_sha256")
    op.drop_constraint(None, "midi_songs", type_="foreignkey")
    # ### end Alembic commands ###
