/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/midi/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Midi
         * @description Generate MIDI events from a natural language prompt.
         *
         *     Args:
         *         request: Generation request with thread_id, constraints, and prompt
         *         db: Database session
         *         user_id: User ID from Authorization header
         *
         *     Returns:
         *         MidiResponse with plan and list of MIDI events
         *
         *     Raises:
         *         HTTPException: If generation fails
         */
        post: operations["generate_midi_api_midi_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/midi/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Conversation
         * @description Restore a previous conversation by thread_id.
         *
         *     Args:
         *         request: Restore request with thread_id
         *         db: Database session
         *         user_id: User ID from Authorization header
         *
         *     Returns:
         *         ConversationRestoreResponse with full conversation history
         *
         *     Raises:
         *         HTTPException: If conversation not found or retrieval fails
         */
        post: operations["restore_conversation_api_midi_restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/midi/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Midi
         * @description Render MIDI events to audio.
         *
         *     Args:
         *         request: Render request with BPM and MIDI events
         *
         *     Returns:
         *         RenderResponse with audio URL, duration, and sample rate
         *
         *     Raises:
         *         HTTPException: If rendering fails
         */
        post: operations["render_midi_api_midi_render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/midi/songs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Songs
         * @description List all songs for the current user.
         *
         *     Args:
         *         db: Database session
         *         user_id: User ID from Authorization header
         *
         *     Returns:
         *         List of SongResponse objects
         *
         *     Raises:
         *         HTTPException: If retrieval fails
         */
        get: operations["list_songs_api_midi_songs__get"];
        put?: never;
        /**
         * Create Song
         * @description Create a new song with an empty track.
         *
         *     Args:
         *         request: Song creation request with title, bpm, and key
         *         db: Database session
         *         user_id: User ID from Authorization header
         *
         *     Returns:
         *         SongResponse with the new song and its empty track
         *
         *     Raises:
         *         HTTPException: If creation fails
         */
        post: operations["create_song_api_midi_songs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/midi/songs/{song_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Song
         * @description Get a specific song with all track details and loops.
         *
         *     Args:
         *         song_id: Song identifier (path parameter)
         *         db: Database session
         *         user_id: User ID from Authorization header
         *
         *     Returns:
         *         SongResponse with tracks and loops
         *
         *     Raises:
         *         HTTPException: If song not found or access denied
         */
        get: operations["get_song_api_midi_songs__song_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/midi/loops/{loop_id}/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Loop Chats
         * @description Get complete chat history for a specific loop.
         *
         *     Args:
         *         loop_id: Loop identifier (path parameter)
         *         db: Database session
         *
         *     Returns:
         *         ChatHistoryResponse with all messages
         *
         *     Raises:
         *         HTTPException: If loop not found
         */
        get: operations["get_loop_chats_api_midi_loops__loop_id__chats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatHistoryResponse
         * @description Response model for chat history.
         */
        ChatHistoryResponse: {
            /**
             * Loop Id
             * @description Loop ID
             */
            loop_id: string;
            /**
             * Messages
             * @description Chat messages in chronological order
             */
            messages: components["schemas"]["ChatMessageResponse"][];
            /**
             * Message Count
             * @description Total number of messages
             */
            message_count: number;
        };
        /**
         * ChatMessageResponse
         * @description Response model for chat messages.
         */
        ChatMessageResponse: {
            /**
             * Id
             * @description Chat message ID
             */
            id: string;
            /**
             * Role
             * @description Message role: 'user' or 'assistant'
             */
            role: string;
            /**
             * Msg
             * @description Message content
             */
            msg: string;
            /**
             * Midi Events
             * @description MIDI events (if any)
             */
            midi_events?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Loop Id
             * @description ID of the associated loop
             */
            loop_id: string;
            /**
             * Created At
             * @description ISO timestamp of message creation
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO timestamp of last update
             */
            updated_at: string;
        };
        /**
         * ConversationMessage
         * @description A message in the conversation history.
         */
        ConversationMessage: {
            /**
             * Role
             * @description Message role: 'user' or 'assistant'
             */
            role: string;
            /**
             * Content
             * @description Message content
             */
            content: string;
            /**
             * Plan Model
             * @description Model used for planning (user messages only)
             */
            plan_model?: string | null;
            /**
             * Generate Model
             * @description Model used for generation (user messages only)
             */
            generate_model?: string | null;
            /**
             * Key
             * @description Musical key constraint (user messages only)
             */
            key?: string | null;
            /**
             * Bpm
             * @description BPM constraint (user messages only)
             */
            bpm?: number | null;
            /**
             * Time Signature
             * @description Time signature constraint (user messages only)
             */
            time_signature?: string | null;
            /**
             * Measures
             * @description Measures constraint (user messages only)
             */
            measures?: number | null;
            /**
             * Plan Data
             * @description Plan data (assistant messages only)
             */
            plan_data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Midi Events
             * @description MIDI events (assistant messages only)
             */
            midi_events?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Created At
             * @description ISO timestamp of message creation
             */
            created_at: string;
        };
        /**
         * ConversationRestoreRequest
         * @description Request to restore a conversation by thread_id.
         */
        ConversationRestoreRequest: {
            /**
             * Thread Id
             * Format: uuid
             * @description Thread identifier to restore
             */
            thread_id: string;
        };
        /**
         * ConversationRestoreResponse
         * @description Response containing conversation history.
         */
        ConversationRestoreResponse: {
            /**
             * User Id
             * Format: uuid
             * @description User identifier
             */
            user_id: string;
            /**
             * Thread Id
             * Format: uuid
             * @description Thread identifier
             */
            thread_id: string;
            /**
             * Messages
             * @description Conversation messages in chronological order
             */
            messages: components["schemas"]["ConversationMessage"][];
            /**
             * Message Count
             * @description Total number of messages
             */
            message_count: number;
        };
        /**
         * CreateSongRequest
         * @description Request payload for creating a new song.
         */
        CreateSongRequest: {
            /**
             * Title
             * @description Song title (optional)
             */
            title?: string | null;
            /**
             * Bpm
             * @description Tempo in BPM (30-360)
             */
            bpm: number;
            /**
             * Key
             * @description Musical key
             * @enum {string}
             */
            key: "Ab" | "A" | "A#" | "Bb" | "B" | "C" | "C#" | "Db" | "D" | "D#" | "Eb" | "E" | "F" | "F#" | "Gb" | "G" | "G#";
        };
        /**
         * GenerateRequest
         * @description Request payload for /api/midi/generate endpoint.
         */
        GenerateRequest: {
            /**
             * Thread Id
             * Format: uuid
             * @description Thread identifier for conversation context
             */
            thread_id: string;
            /**
             * Plan Model
             * @description Model to use for the planning stage
             * @enum {string}
             */
            plan_model: "claude-haiku-4-5" | "claude-sonnet-4-5" | "gpt-4o-mini" | "gpt-4o" | "gpt-5-2" | "gpt-5-mini" | "gpt-5-nano";
            /**
             * Generate Model
             * @description Model to use for the generation stage
             * @enum {string}
             */
            generate_model: "claude-haiku-4-5" | "claude-sonnet-4-5" | "gpt-4o-mini" | "gpt-4o" | "gpt-5-2" | "gpt-5-mini" | "gpt-5-nano";
            /**
             * Key
             * @description Musical key constraint
             */
            key?: ("Ab" | "A" | "A#" | "Bb" | "B" | "C" | "C#" | "Db" | "D" | "D#" | "Eb" | "E" | "F" | "F#" | "Gb" | "G" | "G#") | null;
            /**
             * Bpm
             * @description Tempo constraint in BPM (30-360)
             */
            bpm?: number | null;
            /**
             * Time Signature
             * @description Time signature constraint
             */
            time_signature?: ("3/4" | "4/4" | "5/4" | "6/8" | "7/8") | null;
            /**
             * Measures
             * @description Number of measures to generate (1-32)
             */
            measures?: number | null;
            /**
             * Prompt
             * @description User's musical generation request
             */
            prompt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoopResponse
         * @description Response model for MIDI loops.
         */
        LoopResponse: {
            /**
             * Id
             * @description Loop ID
             */
            id: string;
            /**
             * Title
             * @description Loop title
             */
            title: string;
            /**
             * Measures
             * @description Number of measures in the loop
             */
            measures: number;
            /**
             * Repeat
             * @description Number of times to repeat the loop
             */
            repeat: number;
            /**
             * Midi Events
             * @description MIDI events in the loop
             */
            midi_events: {
                [key: string]: unknown;
            }[];
            /**
             * Track Id
             * @description ID of the parent track
             */
            track_id: string;
            /**
             * Created At
             * @description ISO timestamp of creation
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO timestamp of last update
             */
            updated_at: string;
        };
        /**
         * MidiEvent
         * @description A fully resolved MIDI event with explicit timing.
         */
        MidiEvent: {
            /**
             * Measure
             * @description The measure, starting from 1
             */
            measure: number;
            /**
             * Beat
             * @description The beat within the measure, starting from 1
             */
            beat: number;
            /**
             * Beat Div4
             * @description Divides the beat into quarters (16th notes)
             */
            beat_div4: number;
            /**
             * Beat Div16
             * @description Divides the beat into 16ths (64th notes)
             */
            beat_div16: number;
            /**
             * Event
             * @description MIDI note or CC event
             * @enum {string}
             */
            event: "C-1" | "C#-1" | "Db-1" | "D-1" | "D#-1" | "Eb-1" | "E-1" | "F-1" | "F#-1" | "Gb-1" | "G-1" | "G#-1" | "Ab-1" | "A-1" | "A#-1" | "Bb-1" | "B-1" | "C0" | "C#0" | "Db0" | "D0" | "D#0" | "Eb0" | "E0" | "F0" | "F#0" | "Gb0" | "G0" | "G#0" | "Ab0" | "A0" | "A#0" | "Bb0" | "B0" | "C1" | "C#1" | "Db1" | "D1" | "D#1" | "Eb1" | "E1" | "F1" | "F#1" | "Gb1" | "G1" | "G#1" | "Ab1" | "A1" | "A#1" | "Bb1" | "B1" | "C2" | "C#2" | "Db2" | "D2" | "D#2" | "Eb2" | "E2" | "F2" | "F#2" | "Gb2" | "G2" | "G#2" | "Ab2" | "A2" | "A#2" | "Bb2" | "B2" | "C3" | "C#3" | "Db3" | "D3" | "D#3" | "Eb3" | "E3" | "F3" | "F#3" | "Gb3" | "G3" | "G#3" | "Ab3" | "A3" | "A#3" | "Bb3" | "B3" | "C4" | "C#4" | "Db4" | "D4" | "D#4" | "Eb4" | "E4" | "F4" | "F#4" | "Gb4" | "G4" | "G#4" | "Ab4" | "A4" | "A#4" | "Bb4" | "B4" | "C5" | "C#5" | "Db5" | "D5" | "D#5" | "Eb5" | "E5" | "F5" | "F#5" | "Gb5" | "G5" | "G#5" | "Ab5" | "A5" | "A#5" | "Bb5" | "B5" | "C6" | "C#6" | "Db6" | "D6" | "D#6" | "Eb6" | "E6" | "F6" | "F#6" | "Gb6" | "G6" | "G#6" | "Ab6" | "A6" | "A#6" | "Bb6" | "B6" | "C7" | "C#7" | "Db7" | "D7" | "D#7" | "Eb7" | "E7" | "F7" | "F#7" | "Gb7" | "G7" | "G#7" | "Ab7" | "A7" | "A#7" | "Bb7" | "B7" | "C8" | "C#8" | "Db8" | "D8" | "D#8" | "Eb8" | "E8" | "F8" | "F#8" | "Gb8" | "G8" | "G#8" | "Ab8" | "A8" | "A#8" | "Bb8" | "B8" | "C9" | "C#9" | "Db9" | "D9" | "D#9" | "Eb9" | "E9" | "F9" | "F#9" | "Gb9" | "G9" | "Sustain" | "ModWheel" | "AllNotesOff" | "ResetControllers";
            /**
             * Value
             * @description Velocity or CC value, scaled 0-100
             */
            value: number;
        };
        /**
         * MidiResponse
         * @description Response from /api/midi/generate endpoint including plan and MIDI.
         */
        MidiResponse: {
            /** @description Musical plan from the planning stage */
            plan: components["schemas"]["PlanResponse"];
            /**
             * Midi
             * @description Generated MIDI events
             */
            midi: components["schemas"]["MidiEvent"][];
        };
        /**
         * PlanResponse
         * @description High-level musical plan from the planning stage.
         */
        PlanResponse: {
            /**
             * Key
             * @description The musical key for the composition
             * @enum {string}
             */
            key: "Ab" | "A" | "A#" | "Bb" | "B" | "C" | "C#" | "Db" | "D" | "D#" | "Eb" | "E" | "F" | "F#" | "Gb" | "G" | "G#";
            /**
             * Bpm
             * @description Tempo in beats-per-minute, 30-360
             */
            bpm: number;
            /**
             * Time Signature
             * @description Time signature for the piece
             * @enum {string}
             */
            time_signature: "3/4" | "4/4" | "5/4" | "6/8" | "7/8";
            /**
             * Measures
             * @description Number of measures in the composition (1-32)
             */
            measures: number;
            /**
             * Style
             * @description Brief description of the musical style/feel
             */
            style: string;
            /**
             * Chord Progression
             * @description Chord progression using chord symbols (e.g. ['Gbm7', 'D', 'Em', 'C'])
             */
            chord_progression: string[];
            /**
             * Reasoning
             * @description Explanation of musical choices for evaluation
             */
            reasoning: string;
        };
        /**
         * RenderRequest
         * @description Request payload for /api/midi/render endpoint.
         */
        RenderRequest: {
            /**
             * Bpm
             * @description Tempo in BPM (30-360)
             */
            bpm: number;
            /**
             * Midi
             * @description MIDI events to render
             */
            midi: components["schemas"]["MidiEvent"][];
        };
        /**
         * RenderResponse
         * @description Response from /api/midi/render endpoint with audio information.
         */
        RenderResponse: {
            /**
             * Audio Url
             * @description URL to the rendered audio file
             */
            audio_url: string;
            /**
             * Duration Seconds
             * @description Duration of the audio in seconds
             */
            duration_seconds: number;
            /**
             * Sample Rate
             * @description Sample rate of the audio in Hz
             */
            sample_rate: number;
        };
        /**
         * SongResponse
         * @description Response model for MIDI songs including tracks and loops.
         */
        SongResponse: {
            /**
             * Id
             * @description Song ID
             */
            id: string;
            /**
             * User Id
             * @description User ID who owns the song
             */
            user_id: string;
            /**
             * Title
             * @description Song title
             */
            title: string;
            /**
             * Bpm
             * @description Tempo in BPM
             */
            bpm: number;
            /**
             * Key
             * @description Musical key
             */
            key: string;
            /**
             * Tracks
             * @description Tracks in this song
             */
            tracks?: components["schemas"]["TrackResponse"][];
            /**
             * Created At
             * @description ISO timestamp of creation
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO timestamp of last update
             */
            updated_at: string;
        };
        /**
         * TrackResponse
         * @description Response model for MIDI tracks.
         */
        TrackResponse: {
            /**
             * Id
             * @description Track ID
             */
            id: string;
            /**
             * Song Id
             * @description ID of the parent song
             */
            song_id: string;
            /**
             * Midi Channel
             * @description MIDI channel (1-16)
             */
            midi_channel: number;
            /**
             * Loops
             * @description Loops in this track
             */
            loops?: components["schemas"]["LoopResponse"][];
            /**
             * Created At
             * @description ISO timestamp of creation
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO timestamp of last update
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_midi_api_midi_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MidiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_conversation_api_midi_restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationRestoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRestoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_midi_api_midi_render_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_songs_api_midi_songs__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongResponse"][];
                };
            };
        };
    };
    create_song_api_midi_songs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSongRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_song_api_midi_songs__song_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                song_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_loop_chats_api_midi_loops__loop_id__chats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
