/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/midi/songs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Songs
         * @description List all songs for the current user.
         *
         *     Args:
         *         db: Database session
         *         user_id: User ID from Authorization header
         *
         *     Returns:
         *         List of SongResponse objects
         *
         *     Raises:
         *         HTTPException: If retrieval fails
         */
        get: operations["list_songs_api_midi_songs__get"];
        put?: never;
        /**
         * Create Song
         * @description Create a new song with an empty track.
         *
         *     Args:
         *         request: Song creation request with title, bpm, and key
         *         db: Database session
         *         user_id: User ID from Authorization header
         *
         *     Returns:
         *         SongDetailResponse with the new song and its empty track
         *
         *     Raises:
         *         HTTPException: If creation fails
         */
        post: operations["create_song_api_midi_songs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/midi/songs/{song_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Song
         * @description Get a specific song with all track details and loops.
         *
         *     Args:
         *         song_id: Song identifier (path parameter)
         *         db: Database session
         *         user_id: User ID from Authorization header
         *
         *     Returns:
         *         SongDetailResponse with tracks and loops
         *
         *     Raises:
         *         HTTPException: If song not found or access denied
         */
        get: operations["get_song_api_midi_songs__song_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/midi/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Midi
         * @description Render MIDI events to audio.
         *
         *     Args:
         *         request: Render request with BPM and MIDI events
         *
         *     Returns:
         *         RenderResponse with audio URL, duration, and sample rate
         *
         *     Raises:
         *         HTTPException: If rendering fails
         */
        post: operations["render_midi_api_midi_render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/midi/loops/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Loop
         * @description Create a new MIDI loop.
         */
        post: operations["create_loop_api_midi_loops__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/midi/loops/{loop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Loop
         * @description Get a specific loop with all chat messages.
         */
        get: operations["get_loop_api_midi_loops__loop_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Loop
         * @description Delete a loop and all associated chat messages.
         *
         *     The chat messages are automatically deleted via cascade relationship.
         */
        delete: operations["delete_loop_api_midi_loops__loop_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/midi/loops/{loop_id}/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append Chat
         * @description Create a new user chat message for a loop.
         */
        post: operations["append_chat_api_midi_loops__loop_id__chats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppendChatRequest
         * @description Request model for appending a new chat message to a loop.
         */
        AppendChatRequest: {
            /**
             * Loop Id
             * @description ID of the loop to add the chat message to
             */
            loop_id: string;
            /**
             * Msg
             * @description User message content
             */
            msg: string;
        };
        /**
         * ChatMessageResponse
         * @description Response model for chat messages.
         */
        ChatMessageResponse: {
            /**
             * Id
             * @description Chat message ID
             */
            id: string;
            /**
             * Role
             * @description Message role: 'user' or 'assistant'
             */
            role: string;
            /**
             * Msg
             * @description Message content
             */
            msg: string;
            /**
             * Midi Events
             * @description MIDI events (if any)
             */
            midi_events?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Loop Id
             * @description ID of the associated loop
             */
            loop_id: string;
            /**
             * Created At
             * @description ISO timestamp of message creation
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO timestamp of last update
             */
            updated_at: string;
        };
        /**
         * CreateLoopRequest
         * @description Request model for creating a new loop.
         */
        CreateLoopRequest: {
            /**
             * Track Id
             * @description ID of the parent track
             */
            track_id: string;
            /**
             * Measures
             * @description Number of measures in the loop (1-32)
             */
            measures: number;
            /**
             * Repeat
             * @description Number of times to repeat the loop (default: 1)
             * @default 1
             */
            repeat: number;
        };
        /**
         * CreateSongRequest
         * @description Request payload for creating a new song.
         */
        CreateSongRequest: {
            /**
             * Title
             * @description Song title (optional)
             */
            title?: string | null;
            /**
             * Bpm
             * @description Tempo in BPM (30-360)
             */
            bpm: number;
            /**
             * Key
             * @description Musical key
             * @enum {string}
             */
            key: "Ab" | "A" | "A#" | "Bb" | "B" | "C" | "C#" | "Db" | "D" | "D#" | "Eb" | "E" | "F" | "F#" | "Gb" | "G" | "G#";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoopDetailResponse
         * @description Response model for MIDI loops, including chat message history.
         */
        LoopDetailResponse: {
            /**
             * Id
             * @description Loop ID
             */
            id: string;
            /**
             * Measures
             * @description Number of measures in the loop
             */
            measures: number;
            /**
             * Repeat
             * @description Number of times to repeat the loop
             */
            repeat: number;
            /**
             * Midi Events
             * @description MIDI events in the loop
             */
            midi_events: {
                [key: string]: unknown;
            }[];
            /**
             * Track Id
             * @description ID of the parent track
             */
            track_id: string;
            /**
             * Created At
             * @description ISO timestamp of creation
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO timestamp of last update
             */
            updated_at: string;
            /**
             * Chats
             * @description Chat messages in chronological order
             */
            chats?: components["schemas"]["ChatMessageResponse"][];
        };
        /**
         * LoopResponse
         * @description Response model for MIDI loops, excluding chat message history.
         */
        LoopResponse: {
            /**
             * Id
             * @description Loop ID
             */
            id: string;
            /**
             * Measures
             * @description Number of measures in the loop
             */
            measures: number;
            /**
             * Repeat
             * @description Number of times to repeat the loop
             */
            repeat: number;
            /**
             * Midi Events
             * @description MIDI events in the loop
             */
            midi_events: {
                [key: string]: unknown;
            }[];
            /**
             * Track Id
             * @description ID of the parent track
             */
            track_id: string;
            /**
             * Created At
             * @description ISO timestamp of creation
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO timestamp of last update
             */
            updated_at: string;
        };
        /**
         * MidiEvent
         * @description A fully resolved MIDI event with explicit timing.
         */
        MidiEvent: {
            /**
             * Chord
             * @description Underlying chord in the progression (does not necessarily match the current note)
             */
            chord?: ("I" | "II" | "III" | "IV" | "V" | "VI" | "VII" | "V7" | "I7" | "IV7" | "VI7" | "IIdim" | "VIIdim" | "Vdim" | "Vsus4" | "Isus4" | "Vsus2") | null;
            /**
             * Measure
             * @description The measure, starting from 1
             */
            measure: number;
            /**
             * Beat
             * @description The beat within the measure, starting from 1
             */
            beat: number;
            /**
             * Beat Div4
             * @description Divides the beat into quarters (16th notes)
             */
            beat_div4: number;
            /**
             * Beat Div16
             * @description Divides the beat into 16ths (64th notes)
             */
            beat_div16: number;
            /**
             * Event
             * @description MIDI note or CC event
             * @enum {string}
             */
            event: "C-1" | "C#-1" | "Db-1" | "D-1" | "D#-1" | "Eb-1" | "E-1" | "F-1" | "F#-1" | "Gb-1" | "G-1" | "G#-1" | "Ab-1" | "A-1" | "A#-1" | "Bb-1" | "B-1" | "C0" | "C#0" | "Db0" | "D0" | "D#0" | "Eb0" | "E0" | "F0" | "F#0" | "Gb0" | "G0" | "G#0" | "Ab0" | "A0" | "A#0" | "Bb0" | "B0" | "C1" | "C#1" | "Db1" | "D1" | "D#1" | "Eb1" | "E1" | "F1" | "F#1" | "Gb1" | "G1" | "G#1" | "Ab1" | "A1" | "A#1" | "Bb1" | "B1" | "C2" | "C#2" | "Db2" | "D2" | "D#2" | "Eb2" | "E2" | "F2" | "F#2" | "Gb2" | "G2" | "G#2" | "Ab2" | "A2" | "A#2" | "Bb2" | "B2" | "C3" | "C#3" | "Db3" | "D3" | "D#3" | "Eb3" | "E3" | "F3" | "F#3" | "Gb3" | "G3" | "G#3" | "Ab3" | "A3" | "A#3" | "Bb3" | "B3" | "C4" | "C#4" | "Db4" | "D4" | "D#4" | "Eb4" | "E4" | "F4" | "F#4" | "Gb4" | "G4" | "G#4" | "Ab4" | "A4" | "A#4" | "Bb4" | "B4" | "C5" | "C#5" | "Db5" | "D5" | "D#5" | "Eb5" | "E5" | "F5" | "F#5" | "Gb5" | "G5" | "G#5" | "Ab5" | "A5" | "A#5" | "Bb5" | "B5" | "C6" | "C#6" | "Db6" | "D6" | "D#6" | "Eb6" | "E6" | "F6" | "F#6" | "Gb6" | "G6" | "G#6" | "Ab6" | "A6" | "A#6" | "Bb6" | "B6" | "C7" | "C#7" | "Db7" | "D7" | "D#7" | "Eb7" | "E7" | "F7" | "F#7" | "Gb7" | "G7" | "G#7" | "Ab7" | "A7" | "A#7" | "Bb7" | "B7" | "C8" | "C#8" | "Db8" | "D8" | "D#8" | "Eb8" | "E8" | "F8" | "F#8" | "Gb8" | "G8" | "G#8" | "Ab8" | "A8" | "A#8" | "Bb8" | "B8" | "C9" | "C#9" | "Db9" | "D9" | "D#9" | "Eb9" | "E9" | "F9" | "F#9" | "Gb9" | "G9" | "Sustain" | "ModWheel" | "AllNotesOff" | "ResetControllers";
            /**
             * Value
             * @description Velocity or CC value, scaled 0-100
             */
            value: number;
        };
        /**
         * RenderRequest
         * @description Request payload for /api/midi/render endpoint.
         */
        RenderRequest: {
            /**
             * Bpm
             * @description Tempo in BPM (30-360)
             */
            bpm: number;
            /**
             * Midi
             * @description MIDI events to render
             */
            midi: components["schemas"]["MidiEvent"][];
        };
        /**
         * RenderResponse
         * @description Response from /api/midi/render endpoint with audio information.
         */
        RenderResponse: {
            /**
             * Audio Url
             * @description URL to the rendered audio file
             */
            audio_url: string;
            /**
             * Duration Seconds
             * @description Duration of the audio in seconds
             */
            duration_seconds: number;
            /**
             * Sample Rate
             * @description Sample rate of the audio in Hz
             */
            sample_rate: number;
        };
        /**
         * SongDetailResponse
         * @description Response model for MIDI songs including tracks and loops.
         */
        SongDetailResponse: {
            /**
             * Id
             * @description Song ID
             */
            id: string;
            /**
             * Title
             * @description Song title
             */
            title: string;
            /**
             * Bpm
             * @description Tempo in BPM
             */
            bpm: number;
            /**
             * Key
             * @description Musical key
             */
            key: string;
            /**
             * Created At
             * @description ISO timestamp of creation
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO timestamp of last update
             */
            updated_at: string;
            /**
             * Tracks
             * @description Tracks in this song
             */
            tracks?: components["schemas"]["TrackResponse"][];
        };
        /**
         * SongResponse
         * @description Response model for MIDI songs including tracks and loops.
         */
        SongResponse: {
            /**
             * Id
             * @description Song ID
             */
            id: string;
            /**
             * Title
             * @description Song title
             */
            title: string;
            /**
             * Bpm
             * @description Tempo in BPM
             */
            bpm: number;
            /**
             * Key
             * @description Musical key
             */
            key: string;
            /**
             * Created At
             * @description ISO timestamp of creation
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO timestamp of last update
             */
            updated_at: string;
        };
        /**
         * TrackResponse
         * @description Response model for MIDI tracks.
         */
        TrackResponse: {
            /**
             * Id
             * @description Track ID
             */
            id: string;
            /**
             * Song Id
             * @description ID of the parent song
             */
            song_id: string;
            /**
             * Midi Channel
             * @description MIDI channel (1-16)
             */
            midi_channel: number;
            /**
             * Loops
             * @description Loops in this track
             */
            loops?: components["schemas"]["LoopResponse"][];
            /**
             * Created At
             * @description ISO timestamp of creation
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO timestamp of last update
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_songs_api_midi_songs__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongResponse"][];
                };
            };
        };
    };
    create_song_api_midi_songs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSongRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_song_api_midi_songs__song_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                song_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_midi_api_midi_render_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_loop_api_midi_loops__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLoopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoopDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_loop_api_midi_loops__loop_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoopDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_loop_api_midi_loops__loop_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_chat_api_midi_loops__loop_id__chats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoopDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
